import re

with open('Caracterizacao_Feicao_Erosiva_Plintossolo.qmd', 'r', encoding='utf-8') as f:
    text = f.read()

# Fix in 2.1
text = text.replace(
"""A localidade apresenta clima tropical úmido com estação seca bem definida e chuvas concentradas no inverno (As, segundo classificação de Köppen), predominantemente entre os meses de abril e setembro [@duarte_santos_castelhano_2021]. A precipitação média anual é de aproximadamente 1.400 mm, com máxima mensal em maio (164,7 mm) e mínima em novembro (43,9 mm), conforme série climatológica de 2005 a 2025 (Figura 6). A temperatura média anual situa-se em torno de 25 °C, com amplitude térmica reduzida ao longo do ano. Os solos dominantes são classificados como Neossolo Flúvico Psamítico, Argissolo Vermelho-Amarelo Distrófico e Plintossolo Háplico Distrófico [@nascimento_pedrotti_2004].\n\nO relevo regional apresenta-se diversificado, com predominância de superfícies planas a suavemente onduladas nas áreas elevadas dos tabuleiros [@azambuja_missura_araujo_2024]. No local de implantação, predomina o relevo ondulado a muito ondulado, com declividades locais de 7% a 24% na vertente, desencadeando alto gradiente hidráulico sobre os solos incisáveis.\n\nO entorno da área de estudo apresenta predomínio de relevo ondulado a muito ondulado e convergência de escoamento em linhas preferenciais (Figura 1).""",
"""A localidade apresenta clima tropical úmido com estação seca bem definida e chuvas concentradas no inverno (As, segundo classificação de Köppen), precipitação média anual de 1.400 mm e solos dominantes classificados como Neossolo Flúvico Psamítico, Argissolo Vermelho-Amarelo Distrófico e Plintossolo Háplico Distrófico [@nascimento_pedrotti_2004; @duarte_santos_castelhano_2021]. Concomitantemente, o relevo regional diversificado transita para superfícies muito onduladas no local de implantação, onde declividades de 7% a 24% na vertente desencadeiam alto gradiente hidráulico e convergência de escoamento em linhas preferenciais (Figura 1).""")

# Fix in 2.3
text = text.replace(
"""O processamento fotogramétrico para geração do Modelo Digital de Elevação (MDE) e nuvem de pontos (densidade média de 120 pontos/m²) foi realizado no software Agisoft Metashape Professional Edition 1.6 (versão de avaliação). Não foram utilizados pontos de controle terrestres (GCPs), de modo que a acurácia posicional depende exclusivamente do GNSS embarcado na aeronave (precisão nominal XY ≈ 1,5 m, Z ≈ 0,5 m). Essa limitação não afeta as medidas morfométricas relativas (profundidade, largura, comprimento) realizadas sobre os ortomosaicos, mas restringe a georreferenciação absoluta.\n\nA avaliação morfométrica das incisões erosivas consistiu em mensuração de largura (topo, média e base), comprimento total ao longo da rampa e profundidade nas seções superior, média e inferior de cada feição, desde suas margens iniciais até o leito mais profundo. Para contextualização temporal da evolução morfológica, foi conduzida análise multitemporal comparando imagens de satélite e ou ortofotos disponíveis em base aberta, por exemplo Google Earth, cobrindo o período de 2007 a 2023 (16 anos), permitindo rastreamento de alterações em cobertura vegetal e área de solo exposto. \n\nSeis incisões erosivas foram identificadas e medidas sistematicamente na área, suportadas pela geração de ortomosaicos aéreos, que se consolidam como técnica acurada para reconstrução topográfica de ravinas e voçorocas [@raj_et_al_2022; @wilkinson_et_al_2024].""",
"""A partir desse imageamento, o processamento fotogramétrico (Agisoft Metashape 1.6) gerou Modelo Digital de Elevação (MDE) e nuvem de pontos (120 pontos/m²), cujas métricas relativas viabilizaram a avaliação morfométrica detalhada de largura, comprimento e profundidade nas seções das feições. Consequentemente, seis incisões erosivas foram identificadas e medidas sistematicamente na área, suportadas pela geração de ortomosaicos aéreos que se consolidam como técnica acurada para reconstrução topográfica [@raj_et_al_2022; @wilkinson_et_al_2024]. Para contextualização da evolução morfológica, conduziu-se adicionalmente análise multitemporal de imagens orbitais (2007–2023), rastreando alterações na cobertura vegetal e na exposição do solo.""")

# Fix in 2.4
text = text.replace(
"""O enquadramento foi fundamentado na integração de medidas morfométricas de campo, interpretação visual de ortomosaicos de alta resolução e análise de Modelo Digital de Elevação derivado do processamento fotogramétrico, permitindo inferência da organização espacial das feições, padrões de convergência de escoamento superficial e potencial conectividade hidrológica.\n\nA caracterização climática do regime de chuvas foi obtida a partir de série diária de precipitação agregada para o período de 2005 a 2025 no município de São Cristóvão (n=7.305 dias), transformada em climatologia mensal visando identificar as janelas sazonais de maior propensão à geração de escoamento concentrado [@duarte_santos_castelhano_2021] e, em decorrência, à intensificação de erosão linear sob as condicionantes edáficas pré-existentes.""",
"""Esse enquadramento fundamentou-se na integração de medidas morfométricas de campo e na interpretação visual dos ortomosaicos acoplada ao Modelo Digital de Elevação, permitindo inferência espacial e identificação de conectividade hidrológica. Paralelamente, o regime de chuvas (série diária 2005–2025) subsidiou a identificação das janelas sazonais de máxima propensão à geração de escoamento concentrado [@duarte_santos_castelhano_2021], forçante que condiciona a intensificação da erosão linear no substrato estudado.""")

# Fix in 3.1
text = text.replace(
"""A forma em planta é linear em cinco das seis feições (Feições 2, 3, 4, 5 e 6). A Feição 1 exibe conformação dendrítica com ramificações laterais, padrão morfodinâmico clássico que reflete intensificação de incisão vertical combinada com erosão lateral de margens coesas sob forte convergência de escoamento no topo do vale [@sidorchuk_2006].\n\nA seção transversal predominante em "V" (Tabela 2) indica dominância de incisão vertical sob escoamento concentrado, processo governado pela tensão cisalhante no leito (Equação 3), que supera a resistência do material nas declividades de 8–17% dos terços intermediários. \n\nEssa geometria é característica de solos com elevada fração argilosa e estrutura consolidada em subsuperfície, condição verificada no Plintossolo Argilúvico Distrófico da área (49–51% de argila nos horizontes BAc e Bt, Tabela 1). Em estágio inicial de evolução, a incisão vertical precede o alargamento lateral, ao passo que a transição para geometrias trapezoidais ou em "U" responde ao aumento da energia do escoamento ou à redução da coesão efetiva sob saturação [@sidorchuk_2006]. \n\nA Feição 1 já exibe seção em "U" na base de seus braços dendríticos, sinalizando intensificação do colapso de taludes e retrabalhamento lateral por perda de resistência ao cisalhamento sob pressões neutras elevadas durante os meses de maior precipitação (abril–agosto). A transição de seções em "V" para "U" é reconhecida como indicador de maturação geomorfológica de ravinas, na qual o processo dominante migra da incisão vertical para o alargamento lateral por ruptura gravitacional de paredes [@bull_kirkby_1997; @kirkby_bracken_2009]. \n\nPodwojewski et al. [@podwojewski_et_al_2020], ao monitorarem ravinas (dongas) em pastagem subúmida na África do Sul, documentaram que a expansão lateral ocorre por episódios discretos de colapso de taludes durante eventos de saturação, com taxas de recuo lateral de 0,1–0,5 m/ano, mecanismo análogo ao observado na Feição 1 sob o regime sazonal dos Tabuleiros Costeiros. \n\nEsse padrão reproduz a evolução não linear descrita por Dey et al. [@dey_et_al_2018], na qual a trajetória morfológica das ravinas resulta do acoplamento entre energia cinética do escoamento, resistência geotécnica do material e frequência de episódios de saturação, e é consistente com o modelo conceitual de Kirkby e Bracken [@kirkby_bracken_2009], segundo o qual paredes íngremes são mantidas por mass movements recíprocos que controlam a razão largura/profundidade ao longo do tempo.""",
"""Morfologicamente, a forma em planta é linear em cinco das feições, enquanto a Feição 1 exibe conformação dendrítica sugestiva de intensificação de incisão vertical combinada com erosão lateral sob forte convergência de fluxo [@sidorchuk_2006]. Ademais, a predominância de seções transversais em "V" (Tabela 2) corrobora a dominância de incisão vertical sob escoamento concentrado nas declividades de 8–17%, um comportamento geométrico característico de solos com elevada fração argilosa e estrutura consolidada em subsuperfície (49–51% de argila nos horizontes BAc e Bt). Em estágios iniciais, a incisão vertical precede o alargamento, porém a Feição 1 já exibe seção em "U" na base de seus braços, sinalizando intenso colapso de taludes associado à perda de resistência ao cisalhamento sob as pressões neutras das chuvas sazonais (abril–agosto). \n\nEssa transição geométrica de "V" para "U" demarca a maturação geomorfológica em que o mecanismo dominante migra para o alargamento lateral tangenciado pela ruptura gravitacional das paredes [@bull_kirkby_1997; @kirkby_bracken_2009]. De modo análogo a registros em pastagens subúmidas sul-africanas [@podwojewski_et_al_2020], a expansão lateral observada parece ocorrer por episódios discretos de colapso durante eventos de saturação extrema. O padrão documentado reproduz a evolução não linear parametrizada por Dey et al. [@dey_et_al_2018], na qual a trajetória espelha o acoplamento cíclico entre energia cinética da enxurrada e a resistência edáfica, controlando progressivamente a razão largura/profundidade.""")

text = text.replace(
"""Rengers e Tucker [@rengers_tucker_2015], mediante monitoramento com laser terrestre (TLS), quantificaram que a erosão em plunge pool e o wash sobre a face do headcut respondem por 60–80% do volume total erodido na cabeceira, mecanismo consistente com o acúmulo de material colapsado observado na base das Feições 4 e 5. As feições mais rasas (2, 3 e 6) exibem cabeças suaves, sinalizando estágio inicial de incisão no qual o aprofundamento vertical ainda não atingiu profundidade suficiente para desencadear instabilidade de taludes. Cabeças escarpadas tendem a acelerar o avanço a montante entre maio e agosto, período em que a saturação antecedente acumulada reduz a infiltração efetiva a valores inferiores à VIB estabilizada (1,5 cm/h no terço intermediário), amplificando o volume de escoamento disponível para erosão regressiva [@flores_cervantes_et_al_2006; @vanmaercke_et_al_2021].\n\nTodas as feições permaneceram abaixo de 3 m de profundidade, limiar que a EGC estabelece para classificação como voçoroca. Contudo, a evolução regressiva ativa, a ausência de cobertura vegetal e as declividades de 7–24% indicam suscetibilidade à progressão morfométrica futura.""",
"""Esse mecanismo, quantificado por Rengers e Tucker [@rengers_tucker_2015] como responsável por até 80% do volume erodido na cabeceira, corrobora o acúmulo de material desprendido verificado na base das Feições 4 e 5. Em contraste, as incisões mais rasas (Feições 2, 3 e 6) conservam cabeças suaves por carecerem do aprofundamento vertical e desequilíbrio necessários à instabilidade dos taludes. Acelerações no avanço a montante são esperadas entre maio e agosto, quando a saturação antecedente restringe a infiltração efetiva, amplificando o deflúvio disponível para erosão regressiva [@vanmaercke_et_al_2021]. Consequentemente, embora todas as feições permaneçam morfometricamente abaixo do limiar de 3 m da EGC para classificação como voçoroca, a atividade regressiva contínua, somada à exposição dos argilominerais e ao forte declive (7–24%), sustenta a suscetibilidade eminente à progressão estrutural contínua.""")

# Fix in 3.2 (removed due to length, only keeping structural PCA part)
text = text.replace(
"""O Plintossolo Argilúvico Distrófico apresenta quatro horizontes (Ap, AB, BAc, Bt) com restrições progressivas em profundidade (Tabela 1). Os horizontes BAc e Bt contêm 49,2% e 51,4% de argila, respectivamente, com pH 4,5–4,6, alumínio trocável de 3,7–5,9 cmol~c~/dm³ e saturação por bases de apenas 9,5–13,6%. \n\nA baixa saturação por bases e a saturação por alumínio superior a 80% (Tabela 1) são consistentes com a ausência de cobertura vegetal observada nas feições, ampliando a exposição do solo ao escoamento concentrado. Quando saturados, esses horizontes perdem resistência ao cisalhamento por aumento de pressões neutras, favorecendo instabilidade de taludes e recuo de cabeceira na estação chuvosa [@cassol_et_al_2023; @firoozi_firoozi_2024].\n\nOs horizontes subsuperficiais argilosos conferem coesão quando secos, porém reduzem a condutividade hidráulica sob saturação sazonal [@viana_et_al_2011; @shah_et_al_2017], concentrando o escoamento excedente em canais preferenciais. A cobertura vegetal observada é predominantemente arbustivo-arbórea com folhas coriáceas, padrão compatível com a toxicidade por alumínio e a baixa fertilidade natural [@de_oliveira_et_al_2024; @cassol_et_al_2023].""",
"""O substrato exibe horizontes com restrições progressivas em profundidade, sendo que as camadas BAc e Bt impõem textura muito argilosa (~50%), pH acentuadamente ácido (4,5) e saturação por alumínio superior a 80% (Tabela 1). Esse conjunto compromete o sistema radicular e a cobertura vegetal basal, agravando a exposição física das margens à enxurrada [@de_oliveira_et_al_2024]. Além diso, enquanto esses horizontes conferem forte coesão aparente no período seco, a supressão drástica de permeabilidade condicionada pela mineralogia resulta na rápida elevação da pressão neutra no umedecimento sazonal [@viana_et_al_2011]. Nesse estado, as subcamadas saturadas colapsam sua resistência ao cisalhamento, servindo como o facilitador primário para as dinâmicas de instabilidade dos taludes e avanço progressivo das cabeceiras [@firoozi_firoozi_2024].""")

with open('Caracterizacao_Feicao_Erosiva_Plintossolo.qmd', 'w', encoding='utf-8') as f:
    f.write(text)