# coding: utf-8
import sys

filepath = '2-CARACTERIZACAO_FEICAO/Caracterizacao_Feicao_Erosiva_Plintossolo.qmd'
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

# Fix in 3.1
orig_31 = """A forma em planta é linear em cinco das seis feições (Feições 2, 3, 4, 5 e 6). A Feição 1 exibe conformação dendrítica com ramificações laterais, padrão morfodinâmico clássico que reflete intensificação de incisão vertical combinada com erosão lateral de margens coesas sob forte convergência de escoamento no topo do vale [@sidorchuk_2006].\n\nA seção transversal predominante em "V" (Tabela 2) indica dominância de incisão vertical sob escoamento concentrado, processo governado pela tensão cisalhante no leito (Equação 3), que supera a resistência do material nas declividades de 8–17% dos terços intermediários. \n\nEssa geometria é característica de solos com elevada fração argilosa e estrutura consolidada em subsuperfície, condição verificada no Plintossolo Argilúvico Distrófico da área (49–51% de argila nos horizontes BAc e Bt, Tabela 1). Em estágio inicial de evolução, a incisão vertical precede o alargamento lateral, ao passo que a transição para geometrias trapezoidais ou em "U" responde ao aumento da energia do escoamento ou à redução da coesão efetiva sob saturação [@sidorchuk_2006]. \n\nA Feição 1 já exibe seção em "U" na base de seus braços dendríticos, sinalizando intensificação do colapso de taludes e retrabalhamento lateral por perda de resistência ao cisalhamento sob pressões neutras elevadas durante os meses de maior precipitação (abril–agosto). A transição de seções em "V" para "U" é reconhecida como indicador de maturação geomorfológica de ravinas, na qual o processo dominante migra da incisão vertical para o alargamento lateral por ruptura gravitacional de paredes [@bull_kirkby_1997; @kirkby_bracken_2009]. \n\nPodwojewski et al. [@podwojewski_et_al_2020], ao monitorarem ravinas (dongas) em pastagem subúmida na África do Sul, documentaram que a expansão lateral ocorre por episódios discretos de colapso de taludes durante eventos de saturação, com taxas de recuo lateral de 0,1–0,5 m/ano, mecanismo análogo ao observado na Feição 1 sob o regime sazonal dos Tabuleiros Costeiros. \n\nEsse padrão reproduz a evolução não linear descrita por Dey et al. [@dey_et_al_2018], na qual a trajetória morfológica das ravinas resulta do acoplamento entre energia cinética do escoamento, resistência geotécnica do material e frequência de episódios de saturação, e é consistente com o modelo conceitual de Kirkby e Bracken [@kirkby_bracken_2009], segundo o qual paredes íngremes são mantidas por mass movements recíprocos que controlam a razão largura/profundidade ao longo do tempo."""

new_31 = """Morfologicamente, a forma em planta é linear em cinco das feições, enquanto a Feição 1 exibe conformação dendrítica sugestiva de intensificação de incisão vertical combinada com erosão lateral sob forte convergência de fluxo [@sidorchuk_2006]. Ademais, a predominância de seções transversais em "V" (Tabela 2) corrobora a dominância de incisão vertical sob escoamento concentrado nas declividades de 8–17%, um comportamento geométrico característico de solos com elevada fração argilosa e estrutura consolidada em subsuperfície (49–51% de argila nos horizontes BAc e Bt). Em estágios iniciais, a incisão vertical precede o alargamento, porém a Feição 1 já exibe seção em "U" na base de seus braços, sinalizando intenso colapso de taludes associado à perda de resistência ao cisalhamento sob as pressões neutras das chuvas sazonais (abril–agosto). \n\nEssa transição geométrica de "V" para "U" demarca a maturação geomorfológica em que o mecanismo dominante migra para o alargamento lateral tangenciado pela ruptura gravitacional das paredes [@bull_kirkby_1997; @kirkby_bracken_2009]. De modo análogo a registros em pastagens subúmidas sul-africanas [@podwojewski_et_al_2020], a expansão lateral observada parece ocorrer por episódios discretos de colapso durante eventos de saturação extrema. O padrão documentado reproduz a evolução não linear parametrizada por Dey et al. [@dey_et_al_2018], na qual a trajetória espelha o acoplamento cíclico entre energia cinética da enxurrada e a resistência edáfica, controlando progressivamente a razão largura/profundidade."""

text = text.replace(orig_31, new_31)

# Fix in 3.2
orig_32 = """O Plintossolo Argilúvico Distrófico apresenta quatro horizontes (Ap, AB, BAc, Bt) com restrições progressivas em profundidade (Tabela 1). Os horizontes BAc e Bt contêm 49,2% e 51,4% de argila, respectivamente, com pH 4,5–4,6, alumínio trocável de 3,7–5,9 cmol~c~/dm³ e saturação por bases de apenas 9,5–13,6%. \n\nA baixa saturação por bases e a saturação por alumínio superior a 80% (Tabela 1) são consistentes com a ausência de cobertura vegetal observada nas feições, ampliando a exposição do solo ao escoamento concentrado. Quando saturados, esses horizontes perdem resistência ao cisalhamento por aumento de pressões neutras, favorecendo instabilidade de taludes e recuo de cabeceira na estação chuvosa [@cassol_et_al_2023; @firoozi_firoozi_2024].\n\nOs horizontes subsuperficiais argilosos conferem coesão quando secos, porém reduzem a condutividade hidráulica sob saturação sazonal [@viana_et_al_2011; @shah_et_al_2017], concentrando o escoamento excedente em canais preferenciais. A cobertura vegetal observada é predominantemente arbustivo-arbórea com folhas coriáceas, padrão compatível com a toxicidade por alumínio e a baixa fertilidade natural [@de_oliveira_et_al_2024; @cassol_et_al_2023]."""

new_32 = """Geoquimicamente, o Plintossolo Argilúvico Distrófico exibe quatro horizontes (Ap, AB, BAc, Bt) com restrições progressivas, onde as camadas subsuperficiais (BAc e Bt) contêm cerca de 50% de argila, pH fortemente ácido (4,5–4,6) e saturação por alumínio superior a 80% (Tabela 1). Esse ambiente pedológico hostil restringe a colonização radicular e a cobertura herbácea vigorosa, ampliando a exposição direta dos horizontes ao escoamento concentrado. Embora a fração argilosa garanta forte coesão aparente no período seco, a permeabilidade suprimida favorece a rápida elevação das pressões neutras sob umedecimento sazonal [@viana_et_al_2011; @shah_et_al_2017]. Nessa condição, os horizontes saturados sofrem abrupta perda de resistência ao cisalhamento, propiciando ambiente crítico à instabilidade de taludes, recuo de cabeceiras e concentração do excedente hídrico em canais preferenciais [@cassol_et_al_2023; @firoozi_firoozi_2024]."""

text = text.replace(orig_32, new_32)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)
print("Python replacement success")